# Generated by Django 6.0 on 2025-12-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='اسم بنر مورد نظر شما ؟ ')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='اپلود تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک بنر را وارد کنید')),
                ('position', models.CharField(choices=[('بنر اصلی', 'بنر اصلی'), ('بنر محصولات vip', 'بنر محصولات vip'), ('بنر جدید ترین ها', 'بنر جدید ترین ها'), ('بنر تخفیف', 'بنر تخفیف')], db_index=True, max_length=50, verbose_name='جایگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
