# Generated by Django 6.0 on 2025-12-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'بنر', 'verbose_name_plural': 'بنر سایت '},
        ),
    ]
