# Generated by Django 6.0 on 2025-12-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, help_text='اگر تیک خورده باشد پرداخت موفقیت امیز بوده است ', verbose_name='پرداخت شده است ؟'),
        ),
    ]
