# Generated by Django 6.0 on 2026-01-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_alter_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='اسنپ\u200cشات آدرس'),
        ),
    ]
