# Generated by Django 6.0 on 2025-12-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='ORD-000000-00000', editable=False, max_length=50, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, help_text='اگر تیک خورده باشد پرداخت موفقیت\u200cآمیز بوده است', verbose_name='پرداخت شده است؟'),
        ),
    ]
