# Generated by Django 6.0 on 2025-12-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_order_order_number_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='شماره سفارش'),
        ),
    ]
