# Generated by Django 6.0 on 2026-01-07 07:36

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='درباره ما', help_text='عنوان اصلی صفحه درباره ما', max_length=300, verbose_name='عنوان صفحه')),
                ('short_description', models.TextField(help_text='خلاصه\u200cای از معرفی فروشگاه (حداکثر 500 کاراکتر)', max_length=500, verbose_name='توضیحات کوتاه')),
                ('full_description', django_ckeditor_5.fields.CKEditor5Field(help_text='متن کامل درباره فروشگاه با امکان فرمت\u200cبندی', verbose_name='توضیحات کامل')),
                ('mission', models.TextField(blank=True, help_text='شرح ماموریت و هدف اصلی فروشگاه', null=True, verbose_name='ماموریت ما')),
                ('vision', models.TextField(blank=True, help_text='چشم\u200cانداز و اهداف آینده', null=True, verbose_name='چشم\u200cانداز ما')),
                ('image', models.ImageField(blank=True, help_text='تصویر نمایشی صفحه درباره ما', null=True, upload_to='about_us/', verbose_name='تصویر اصلی')),
                ('address', models.TextField(blank=True, help_text='آدرس کامل فروشگاه یا دفتر مرکزی', null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, help_text='شماره تماس اصلی', max_length=11, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, help_text='ایمیل رسمی فروشگاه', max_length=254, null=True, verbose_name='ایمیل')),
                ('working_hours', models.CharField(blank=True, help_text='مثال: شنبه تا پنجشنبه 8 صبح تا 8 شب', max_length=200, null=True, verbose_name='ساعات کاری')),
                ('is_active', models.BooleanField(default=True, help_text='نمایش این صفحه در سایت', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه درباره ما',
                'verbose_name_plural': 'درباره ما',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='نام کامل فرستنده پیام', max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(help_text='آدرس ایمیل برای پاسخگویی', max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, help_text='شماره موبایل 11 رقمی', max_length=11, null=True, verbose_name='شماره تماس')),
                ('subject', models.CharField(help_text='عنوان یا موضوع اصلی پیام', max_length=300, verbose_name='موضوع پیام')),
                ('message', models.TextField(help_text='متن کامل پیام کاربر', verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, help_text='آیا این پیام توسط ادمین خوانده شده؟', verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
                'db_table': 'contact_us',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='متن سوال (حداکثر 500 کاراکتر)', max_length=500, verbose_name='سوال')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(help_text='پاسخ کامل سوال با امکان فرمت\u200cبندی', verbose_name='پاسخ')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('order', 'سفارش و خرید'), ('payment', 'پرداخت'), ('shipping', 'ارسال'), ('return', 'مرجوعی'), ('account', 'حساب کاربری'), ('product', 'محصولات')], default='general', help_text='مثال: خرید، ارسال، پرداخت', max_length=100, verbose_name='دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, help_text='عدد کوچکتر = اولویت بالاتر (0, 1, 2, ...)', verbose_name='اولویت نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='نمایش این سوال در سایت', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'db_table': 'faq',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('twitter', 'توییتر'), ('linkedin', 'لینکدین'), ('youtube', 'یوتیوب'), ('aparat', 'آپارات')], help_text='مثال: اینستاگرام، تلگرام، واتساپ', max_length=100, verbose_name='نام شبکه اجتماعی')),
                ('url', models.URLField(help_text='لینک کامل شبکه اجتماعی', verbose_name='آدرس لینک')),
                ('icon_class', models.CharField(blank=True, help_text='مثال: fab fa-instagram', max_length=100, null=True, verbose_name='کلاس آیکون')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش در سایت', verbose_name='اولویت نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'db_table': 'social_media',
                'ordering': ['order'],
            },
        ),
    ]
