# Generated by Django 6.0 on 2025-12-13 12:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='نام دسته\u200cبندی، مثل: میوه، سبزیجات، ترشیجات', max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, help_text='آدرس URL دسته\u200cبندی، به صورت خودکار از عنوان ساخته می\u200cشود', max_length=200, unique=True, verbose_name='اسلاگ')),
                ('is_main', models.BooleanField(default=False, help_text='اگر این گزینه فعال باشد، این دسته\u200cبندی به عنوان دسته اصلی در نظر گرفته می\u200cشود', verbose_name='دسته\u200cبندی اصلی')),
                ('image', models.ImageField(blank=True, help_text='تصویر نمایشی دسته\u200cبندی (برای صفحه دسته یا منو)', null=True, upload_to='categories/', verbose_name='تصویر دسته\u200cبندی')),
                ('meta_title', models.CharField(help_text='عنوان سئویی صفحه دسته\u200cبندی (حداکثر 60 کاراکتر)', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(help_text='توضیحات سئویی صفحه دسته\u200cبندی (حداکثر 160 کاراکتر)', verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, help_text='اگر غیرفعال باشد، دسته\u200cبندی نمایش داده نمی\u200cشود', verbose_name='وضعیت فعال')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='عدد کمتر یعنی نمایش در جایگاه بالاتر', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد دسته\u200cبندی', verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='آخرین زمان بروزرسانی', verbose_name='تاریخ بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, help_text='اگر این دسته\u200cبندی زیرمجموعه است، دسته\u200cبندی والد را انتخاب کنید', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products_app.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='نام محصول، مثل: سیب زرد ارگانیک', max_length=250, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, help_text='آدرس URL محصول، به صورت خودکار ساخته می\u200cشود', max_length=250, unique=True, verbose_name='اسلاگ')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='توضیحات کامل محصول، امکان درج تصویر، لینک nofollow و محتوای حرفه\u200cای سئویی', verbose_name='توضیحات کامل محصول')),
                ('short_description', models.CharField(help_text='خلاصه توضیح محصول (برای لیست محصولات)', max_length=300, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(help_text='تصویر اصلی محصول که در صفحه محصول نمایش داده می\u200cشود', upload_to='products/', verbose_name='تصویر اصلی محصول')),
                ('price', models.PositiveIntegerField(help_text='قیمت محصول به تومان', verbose_name='قیمت')),
                ('discount_price', models.PositiveIntegerField(blank=True, help_text='در صورت وجود تخفیف، قیمت نهایی محصول', null=True, verbose_name='قیمت با تخفیف')),
                ('stock', models.PositiveIntegerField(help_text='تعداد موجودی محصول در انبار', verbose_name='موجودی')),
                ('is_available', models.BooleanField(default=True, help_text='اگر محصول موجود نیست غیرفعال شود', verbose_name='موجود / ناموجود')),
                ('meta_title', models.CharField(help_text='عنوان سئویی صفحه محصول (حداکثر 60 کاراکتر)', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(help_text='توضیحات سئویی صفحه محصول (حداکثر 160 کاراکتر)', verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, help_text='اگر غیرفعال باشد، محصول در سایت نمایش داده نمی\u200cشود', verbose_name='وضعیت فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد محصول', verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='آخرین زمان بروزرسانی محصول', verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(help_text='دسته\u200cبندی\u200cای که این محصول در آن قرار دارد', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products_app.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
