# Generated by Django 6.0 on 2025-12-24 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_priority',
            field=models.PositiveSmallIntegerField(default=0, max_length=5, verbose_name='امتیاز محول'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='اگر محصول شما ویژه است تیک بزنید ', verbose_name='محصول ویژه است ؟ '),
        ),
        migrations.AddField(
            model_name='product',
            name='vip',
            field=models.BooleanField(default=False, help_text='این بخش برای مشخص کردن محصولات vip میباشد ', verbose_name='محصول vip'),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products_app.productcomment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='products_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: رنگ، وزن، جنس، گارانتی', max_length=100, verbose_name='عنوان ویژگی')),
                ('value', models.CharField(help_text='مثلاً: قرمز، ۱ کیلوگرم، پلاستیک', max_length=255, verbose_name='مقدار ویژگی')),
                ('ordering', models.PositiveSmallIntegerField(default=0, help_text='ترتیب نمایش ویژگی\u200cها در صفحه محصول', verbose_name='اولویت نمایش')),
                ('product', models.ForeignKey(help_text='این ویژگی مربوط به کدام محصول است', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products_app.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصولات',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='تصویر مربوط به گالری محصول', upload_to='products/gallery/', verbose_name='تصویر محصول')),
                ('is_main', models.BooleanField(default=False, help_text='اگر فعال باشد، این تصویر به عنوان تصویر اصلی محصول نمایش داده می\u200cشود', verbose_name='تصویر اصلی')),
                ('ordering', models.PositiveSmallIntegerField(default=0, help_text='عدد کوچک\u200cتر → نمایش زودتر در گالری', verbose_name='اولویت نمایش')),
                ('product', models.ForeignKey(help_text='این تصویر متعلق به کدام محصول است', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products_app.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'تصویر گالری محصول',
                'verbose_name_plural': 'گالری تصاویر محصولات',
                'ordering': ['ordering'],
            },
        ),
    ]
