# Generated by Django 6.0 on 2025-12-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vip',
            field=models.BooleanField(default=False, help_text='این بخش برای مشخص کردن محصولات vip میباشد ', verbose_name='محصول vip'),
        ),
    ]
