# Generated by Django 6.0 on 2026-01-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_featured_priority_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.CharField(blank=True, help_text='نوع یا گروه\u200cبندی محصول', max_length=100, null=True, verbose_name='نوع دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='وزن محصول (بر حسب گرم یا کیلوگرم)', max_digits=6, null=True, verbose_name='وزن'),
        ),
    ]
