# Generated by Django 6.0 on 2025-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='اگر محصول شما ویژه است تیک بزنید ', verbose_name='محصول ویژه است ؟ '),
        ),
    ]
