# Generated by Django 6.0 on 2026-01-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_product_category_type_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='flaticon-vegetable', help_text='نام کلاس آیکون، مثل: flaticon-vegetable', max_length=100, null=True, verbose_name='آیکون'),
        ),
    ]
