# Generated by Django 6.0 on 2025-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_priority',
            field=models.PositiveSmallIntegerField(default=0, max_length=5, verbose_name='امتیاز محول'),
        ),
    ]
