# Generated by Django 6.0 on 2025-12-19 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_product_featured_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: رنگ، وزن، جنس، گارانتی', max_length=100, verbose_name='عنوان ویژگی')),
                ('value', models.CharField(help_text='مثلاً: قرمز، ۱ کیلوگرم، پلاستیک', max_length=255, verbose_name='مقدار ویژگی')),
                ('ordering', models.PositiveSmallIntegerField(default=0, help_text='ترتیب نمایش ویژگی\u200cها در صفحه محصول', verbose_name='اولویت نمایش')),
                ('product', models.ForeignKey(help_text='این ویژگی مربوط به کدام محصول است', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products_app.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصولات',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='تصویر مربوط به گالری محصول', upload_to='products/gallery/', verbose_name='تصویر محصول')),
                ('is_main', models.BooleanField(default=False, help_text='اگر فعال باشد، این تصویر به عنوان تصویر اصلی محصول نمایش داده می\u200cشود', verbose_name='تصویر اصلی')),
                ('ordering', models.PositiveSmallIntegerField(default=0, help_text='عدد کوچک\u200cتر → نمایش زودتر در گالری', verbose_name='اولویت نمایش')),
                ('product', models.ForeignKey(help_text='این تصویر متعلق به کدام محصول است', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products_app.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'تصویر گالری محصول',
                'verbose_name_plural': 'گالری تصاویر محصولات',
                'ordering': ['ordering'],
            },
        ),
    ]
