# Generated by Django 6.0 on 2025-12-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
