# Generated by Django 6.0 on 2025-12-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_productcomment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
