# Generated by Django 6.0 on 2025-12-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_productcomment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز محول'),
        ),
    ]
