# Generated by Django 6.0 on 2025-12-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0009_alter_product_featured_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_priority',
            field=models.PositiveSmallIntegerField(default=0, max_length=5, verbose_name='امتیاز محول'),
        ),
    ]
